CREATE SEQUENCE IF NOT EXISTS booking_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS null_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS room_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS user_seq START WITH 1 INCREMENT BY 50;
